server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/wjnovoam/microservicios-proyectos
          search-paths: config-data
  application:
    name: config-service